wildfly:
  build: wildfly
  ports:
    - 127.0.0.1:8080:8080
    - 127.0.0.1:9990:9990
  links:
    - mongo
  volumes:
    - ./wildfly/deployments:/opt/jboss/wildfly/standalone/deployments:z
  restart: always
mongo:
  image: tutum/mongodb:3.2
  environment:
    - AUTH=no
